steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${SERVICE_NAME}:${GITHUB_SHA}','--build-arg','NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL}', '.']
images: ['gcr.io/${PROJECT_ID}/${SERVICE_NAME}:${GITHUB_SHA}']
